package com.example.myapplication.model

val hardcodedIdeas = listOf(
    Idea(1, "Learn to juggle", "Start with 3 balls and practice daily", "Activities"),
    Idea(2, "Meditate for 10 minutes", "Find a quiet spot and focus on breathing", "Health"),
    Idea(3, "Read a book", "Choose a genre you enjoy and read for 30 minutes", "Learning"),
    Idea(4, "Learn a new language", "Use Duolingo for 15 minutes daily", "Learning"),
    Idea(5, "Go for a walk", "Enjoy nature and get some fresh air", "Health"),
    Idea(6, "Cook a new recipe", "Try something you've never made before", "Activities"),
    Idea(7, "Write in a journal", "Express your thoughts and feelings", "Creativity"),
    Idea(8, "Learn to play an instrument", "Start with basic chords on guitar or piano", "Learning"),
    Idea(9, "Do a random act of kindness", "Make someone's day better", "Social"),
    Idea(10, "Learn a magic trick", "Impress your friends with a simple illusion", "Activities"),
    Idea(11, "Try a new sport", "Pick something you've never played before", "Activities"),
    Idea(12, "Watch a documentary", "Learn something new about the world", "Learning"),
    Idea(13, "Call an old friend", "Reconnect with someone you haven't talked to in a while", "Social"),
    Idea(14, "Draw or sketch something", "You don't need to be an artist to enjoy it", "Creativity"),
    Idea(15, "Try yoga", "Follow a beginner video on YouTube", "Health"),
    Idea(16, "Visit a museum", "Explore art, history or science nearby", "Learning"),
    Idea(17, "Plant something", "Start a small herb garden on your windowsill", "Activities"),
    Idea(18, "Write a short story", "Let your imagination run wild", "Creativity"),
    Idea(19, "Learn to cook a dish from another culture", "Try Thai, Japanese or Mexican cuisine", "Activities"),
    Idea(20, "Do a digital detox", "Spend one day without social media", "Health"),
    Idea(21, "Volunteer locally", "Help out at a shelter or community event", "Social"),
    Idea(22, "Learn origami", "Start with a simple paper crane", "Creativity"),
    Idea(23, "Go stargazing", "Find a dark spot and look up at the night sky", "Activities"),
    Idea(24, "Start a podcast", "Record your thoughts or interview a friend", "Creativity"),
    Idea(25, "Take a cold shower", "Challenge yourself every morning for a week", "Health"),
    Idea(26, "Learn basic photography", "Use your phone and experiment with angles", "Creativity"),
    Idea(27, "Try intermittent fasting", "Skip breakfast and see how you feel", "Health"),
    Idea(28, "Play a board game", "Invite friends or family for a game night", "Social"),
    Idea(29, "Declutter your room", "Donate things you no longer need", "Activities"),
    Idea(30, "Learn to solve a Rubik's cube", "Follow a beginner tutorial step by step", "Learning")
)